### ISSUE TITLE
Serialization of ORCA_Result doesn't work

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/qmworks#19]
The problem seems to be that the plams result object is stored in ORCA_Result

**Comment by felipeZ** [comment]
There is an small test for Orca. Is `qmworks` passing this test?

**Comment by ridderl** [comment]
Which test?
I'm fixing the issue anyway ....

**Comment by felipeZ** [comment]
We have this [test](https://github.com/SCM-NV/qmworks/blob/develop/test/tests_using_plams/opt_orca.py).

**Comment by ridderl** [comment]
OK, that must be recent, I hadn't pulled it yet.

**Comment by ridderl** [comment]
Fixed it again after changes in the result class. Hopefully it stays more stable now ....
