### ISSUE TITLE
components

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#3]
There are several [components](https://github.com/SCM-NV/qmworks/tree/clean/qmworks/components) modules that are not export by the package. Are they operational?

**Comment by ridderl** [comment]
Which "components modules" do you mean?

**Comment by felipeZ** [comment]
Follow this link: [components](https://github.com/SCM-NV/qmworks/tree/master/qmworks/components)

**Comment by ridderl** [comment]
Yes I followed the link, but I still don't understand the issue. All files are imported in the __init__

**Comment by felipeZ** [comment]
Sorry, I forgot to mention that the components module is commented in the **__init__.py** file of qmworks. So I'm not sure how you are using them.

**Comment by ridderl** [comment]
Ah, OK, I wasn't aware. In my scripts I import as follows:
`from qmworks.components import PES_scan, select_max`
That works anyway. So, yes, this code is operational.

**Comment by felipeZ** [comment]
I will add then to the __init__.py file
