### ISSUE TITLE
Raise error when a generic keyword is not recognized by a package

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/qmworks#32]

**Comment by felipeZ** [comment]
That is already done in the definition of ``__getattr__`` in class [Results](https://github.com/SCM-NV/qmworks/blob/master/qmworks/packages/packages.py#L80):
```python
    def __getattr__(self, prop):
        """Returns a section of the results.

        Example:

        ..
            dipole = result.dipole
        """
        if prop in self.prop_dict:
            return self.get_property(prop)
        else:
            raise KeyError("Generic property '" + str(prop) + "' not defined")

```

**Comment by ridderl** [comment]
No I mean generic keywords in the settings, it means we should raise a RuntimeError in handle_special_keywords it the key is not found. I now see it is already done in ADF, but not in DFTB. I will do it. Not sure about the other packages.

**Comment by felipeZ** [comment]
Ok, I will do it for gamess, Orca and Cp2k

**Comment by felipeZ** [comment]
Can We make a list of all the special keywords that should be implemented in all packages?

### Keywords:
  * basis

**Comment by ridderl** [comment]
Actually a warning might be better. Sometimes I want to quickly test a workflow by replacing a package by DFTB, and for sure DFTB doesn't have some of the keywords (e.g. `basis`)

I think we should introduce a logger, so we can use different warning levels. Then the script can be run at different tolerance levels as well.

**Comment by felipeZ** [comment]
What about an [UserWarning](https://docs.python.org/3.1/library/exceptions.html#UserWarning)?

**Comment by felipeZ** [comment]
like:
```python
from warnings import warn
msg = "Beware!"
warn(UserWarning(msg))
```

**Comment by ridderl** [comment]
OK, let's use that ....
