### ISSUE TITLE
Generic keywords

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/qmworks#34]
Are we happy with the format of the generic2package.json files?
- The interpretation of the json relies on the qmworks Settings subclass which interprets `["key1.key2"]` as `["key1"]["key2"]`. If possible if would be great if we could stick to the plams Settings somehow. But: I don't know how to implement e.g. the `basis` becomes `basis.type` modification using just plams Setttings.
- Currently, if values in the dictionary are a list (of two items) the first item is the specific keyword and the second item is a specific value. If the second item is a dictionary, the dictionary defines how to translate the user specified generic value to a package specific value (see https://github.com/SCM-NV/qmworks/blob/master/qmworks/data/dictionaries/generic2ADF.json). This is not very intuitive.
- One improvement could be to use a "key" and "value" attribute, so: 

```
"generic_key": {
    "key": "specific_key",
    "value": "specific_value"}
```
- Then still specific_value could be a dictionary defining how a user provided generic value should be translated into a package specific value.

Any idea's?

**Comment by ridderl** [comment]
Felipe, I tried to do a constrained optimization in ORCA.
This is the settings to freeze atoms 1 to 3:
```
specific: 	
         orca: 	
              geom: 	
                   Constraints: 	
                               { C 1 C }: 	None
                               { C 2 C }: 	None
                               { C 3 C }: 	None
```
I would like to get something like this in the ORCA input (which would work, I tried it):
```
%geom Constraints
        { C 1 C }
        { C 2 C }
        { C 3 C }
        end
      end
```
But I get this:
```
%geom Constraints { C 1 C }: 	None
{ C 2 C }: 	None
{ C 3 C }: 	None

      end
```

This seems to be a problem in orcajob.py of plams. Could you please have a look at this?

**Comment by felipeZ** [comment]
Could you please give me the input file?

**Comment by ridderl** [comment]
Here is a script illustrating the above issue:
```
from qmworks import orca, run, Settings, templates, molkit

methanol = molkit.from_smiles('CO')

# optimize only H atoms
s = Settings()
s.specific.orca.geom.Constraints['{ C 0 C }'] = None
s.specific.orca.geom.Constraints['{ C 1 C }'] = None
s.specific.orca.geom.Constraints['{ C 2 C }'] = None

partial_opt = orca(templates.geometry.overlay(s), methanol, job_name='part_opt')

print(run(partial_opt).molecule) 
```

**Comment by felipeZ** [comment]
I have try the following script in Cartesius and it works.
```python
from plams import Molecule
from qmworks import (orca, run, Settings, templates)

methanol = Molecule('methanol.xyz')

# optimize only H atoms
s = Settings()
s.specific.orca.geom.Constraints._end = '{ C 0 C } { C 1 C } { C 2 C }'

partial_opt = orca(templates.geometry.overlay(s), methanol, job_name='part_opt')

print(run(partial_opt).molecule)
```
The  keyword  ``_end``  comes from the fact that in Orca the  *end* keyword is mandatory for only a subset of sections and there is not a clear rule when the user should an ``end``. Therefore it is possible to add such ``end`` in the Settings.

But if you are planing that the constrains should look like:
```python
s.specific.orca.geom.Constraints['{ C 0 C }']
s.specific.orca.geom.Constraints['{ C 1 C }']
s.specific.orca.geom.Constraints['{ C 2 C }']

```
We then need to change PLAMS.

**Comment by ridderl** [comment]
OK, I implemented the generic constraints settings for ORCA, using the _end  keyword for the time being. See issue #41.
