### ISSUE TITLE
Gamess crashes when symmetry is not defined

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/qmworks#35]
When a gamess job is started without symmetry definition, plams selects by default C1 symmetry. However, it then crashes with the follow error:
```
 THE POINT GROUP OF THE MOLECULE IS C1      
 THE ORDER OF THE PRINCIPAL AXIS IS     0


 *** ERROR!
 BLANK CARD FOUND WHILE TRYING TO READ INPUT ATOM    1
 POSSIBLE ERRORS INCLUDE:
 1. C1 GROUP SHOULD NOT HAVE A BLANK CARD AFTER IT.
```

Plams puts an empty line after the line specifying the symmetry, Apperently this is wrong with C1, but it is fine with other symmetries like Cs. Pretty weird behavior of Gamess, but confirmed on slide 26 of http://www.msg.ameslab.gov/tutorials/gamessintro.pdf

Needs to be solved in plams/gamessjob.py, function print_molecule

**Comment by felipeZ** [comment]
Issue was solve in Plams [master branch](https://github.com/SCM-NV/PLAMS/commit/fdef5be0914ea46cc42fdb0acd0d66adf330d895)
