### ISSUE TITLE
run_job and handle_special_keywords methods should be staticmethods

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#38]
The ``Package`` class requires that its children implement the method [run_job](https://github.com/SCM-NV/qmworks/blob/develop/qmworks/packages/packages.py#L234) and [handle_special_keywords](https://github.com/SCM-NV/qmworks/blob/develop/qmworks/packages/packages.py#L227). These methods do not use the self object for any operation but belong to the ``Package`` class. Therefore these method should be static.

**Comment by ridderl** [comment]
Fine!
