### ISSUE TITLE
Move examples to test and remove plams.init() calls

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#40]
the `Plams.init` command is not longer necessary. See ths [issue](https://github.com/SCM-NV/qmworks/issues/38)
 I already removed it from the test suite and now we should remove it from the examples.

**Comment by ridderl** [comment]
Hi Felipe, for me the tests without function, e.g. test_ADF3FDE_Dialanine.py, don't work yet.

**Comment by felipeZ** [comment]
Yes, those tests are not working so I have excluded them from the *travis* building. Do you want me to exclude them from somewhere else?

**Comment by ridderl** [comment]
I'm able to fix the test in test_ADF3FDE_Dialanine.py if I put the code in a function called `test_ADF3FDE_Dialanine`, but I do not succeed without using a function.
Are you sure it should be possible to run a test script which does not define a function?

**Comment by felipeZ** [comment]
according to the [nose](http://nose.readthedocs.io/en/latest/finding_tests.html) documentation, it looks for all the files and folders following the test regular expression. Actually I excluding explicitly the FDE test suite because they are broken and fail when travis try to build the package (also travis is not aware of any ADF installation).

**Comment by ridderl** [comment]
I don't get your point about excluding just the FDE tests. I think they should be treated just like the other tests that need the packages to run.

**Comment by felipeZ** [comment]
Right now the travis script that handles the testing looks like:
```
  - nosetests --with-coverage --cover-erase --cover-package=qmworks -a 'fast' --exclude='test_using_plams' -v
```
I'm ignoring the whole ``test_using_plams`` folder. But When I  try the tests in Cartesius I run

```
  nosetests --with-coverage --cover-erase --cover-package=qmworks --exclude='.*FDE.*' -v
```
Because the FDE tests are broken. if you do not exclude anything all the python script starting with ``tests`` are going to be executed.

The following command run all the tests,
```
  nosetests --with-coverage --cover-erase --cover-package=qmworks  -v
```

**Comment by ridderl** [comment]
I know the FDE code is currently not working as a test. 
But we should fix that and include it as a test.

**Comment by ridderl** [comment]
I will fix it.

**Comment by ridderl** [comment]
I moved the FDE examples to a new `qmworks/examples/FDE_Fragments` folder.
Also I created `test_FDE_Fragments.py` in the test_using_plams folder which tests the code in the examples/FDE_Fragments folder.
I think this is a good way to have simple example code and still be able to test it automatically. So I would like to move some other test code in the same way to the examples folder.

Do you like it?

**Comment by felipeZ** [comment]
Yes, I think is a good Idea.
