### ISSUE TITLE
Remove Exec dependencies and hidden function in __init__ files

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#45]
I think that functions should not been in the [__init__.py](https://github.com/SCM-NV/qmworks/blob/develop/test/__init__.py) modules. It causes unexpected behavior.  Also, the Python community in general disencourage the use of the ``exec`` function, because it can cause nasty bugs.

**Comment by felipeZ** [comment]
For instances trying to run the following command:
```bash
nosetests test --with-coverage --cover-erase --cover-package=qmworks --cover-xm -v   
```
Run all the test correctly, but generates the plams output for all the test files in the ``examples\Constrained_and_TS_optimizations``
Because the ``tests`` scripts are linked to the ``examples``  and the first ``test`` to call the ``run`` method set the ``CWD`` as the plams default folder.

**Comment by ridderl** [comment]
I designed the examples such that they don't need to read files from the example folders. As a result the tests don't need to change the cwd, solving this issue.

If you are happy with this solution please close the issue :-)
