### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by sgu800** [SCM-NV/qmworks#5]
User *Settings* should get preference over defaults *Settings*. But now it is printing both user and settings in the case of functionals. For example look at the XC section of following example script where it prints both PBE and LDA, where it should only give preference to PBE(user preferred functional). It should be fixed as we are now having more people started using our code. 
`# Default imports
from qmworks import Settings, templates, run
from noodles import gather
from plams import Molecule

from qmworks.packages.SCM import adf

import plams
# ========== =============

plams.init()

import os
import sys
import fnmatch
from os.path   import join

path = "/home/ganga/Workflows/Workflows3/Ayers/WithoutDFTBHessian/Moleculeswithmul2"
files     = os.listdir(path)
xyzFiles  = filter(lambda x: fnmatch.fnmatch(x,"*.xyz"), files)
pathsXYZ  = map(lambda x: join(path,x), xyzFiles)
molecules = [Molecule(name, 'xyz') for name in pathsXYZ]

settings = Settings()
settings.functional = "pbe"
settings.basis = "TZ2P"
settings.specific.adf.charge = "0 2"
settings.specific.adf.unrestricted = ""

job_list = []
for m in molecules:
    ts = adf(templates.ts.overlay(settings),m)
    job_list.append(adf(templates.freq.overlay(settings), ts.molecule))

wf = gather(*job_list)

results = run(wf, n_processes = 1)`

````
Scf
  Converge 1e-06
  Iterations 100
End

Xc
    Gga PBE
    Lda
End

End Input
```

**Comment by ridderl** [comment]
I fixed this issue by introducing the special Settings keyword "__block _replace"
```
__block_replace = True
```
results in removing all existing key value pairs in the current node of the settings tree.

For example:
```
from qmworks import Settings
t = Settings()
t.input.xc.lda = ""
u = Settings()
u.input.xc.hybrid = 'b3lyp'
print(t.overlay(u))

        input:
              xc:
                 hybrid:     b3lyp
                 lda:

u.input.xc.__block_replace = True
print(t.overlay(u))

        input:
              xc:
                 __block_replace:     True
                 hybrid:     b3lyp
```

I added the __block_replace keyword already in the templates, so you don't need to add __block_replace to your user settings. It should just work know. Please try and let me know if you encounter any issues.

**Comment by ridderl** [comment]
By the way: these recent changes are currently only in the "develop" branch of qmworks

**Comment by sgu800** [comment]
Dear Lars,

I have tested it and I got a following error "RuntimeError: dictionary changed size during iteration"., which is related to templates.
[slurm-2272394.txt](https://github.com/SCM-NV/qmworks/files/361580/slurm-2272394.txt)

Kind regards,
Satesh

**Comment by ridderl** [comment]
Hi Satesh,

I cannot reproduce this problem, which your reported quite some time ago. Is it still occurring on your side?

Regards,
Lars

**Comment by sgu800** [comment]
Dear Lars,

I have tested them again and it is not occurring now.

Regards,
Satesh
