### ISSUE TITLE
Status Change

### ISSUE THREAD

**Issue by sgu800** [SCM-NV/qmworks#56]
Dear All,

I am querying for status to be successful (status == successful) in my workflow to print results. But I found that for some reason instead of status == successful, it is writing status ==copied after workflow execution and it obviously not print the results for me.

Many thanks in advance,
Satesh

**Comment by jhidding** [comment]
Hi Satesh, I need a bit more detail here.

**Comment by felipeZ** [comment]
We are defining the Result class like:
```python
class Result:
    """
    Class containing the result associated with a quantum chemistry simulation.
    """
    def __init__(self, settings, molecule, job_name, plams_dir=None,
                 work_dir=None, properties=None, status='done'):
```
The last attribute called `status` depends on the *Plams* status. This status could be: `successful`, `crash`, `copied` or `failed`.
When a Workflow finishes successfully all the `job.status` are  `successful`.  But when I job is `retrieve` by noodles the new status is changed to `copied` by *Plams*.

**Comment by ridderl** [comment]
That's weird.
If noodles retrieves the result, there should not be a call to plams, right? So how come the status is being changed?

**Comment by felipeZ** [comment]
When you retrieve the property using the `rkf` or `t21` file from the `cache.json` the method [_prepare](https://github.com/SCM-NV/PLAMS/blob/898f295254e8a7182b21c07287ecf832eabe92a8/src/scm/plams/basejob.py#L162) from `plams.Job` class is somehow invoked. This method changed the status.

**Comment by ridderl** [comment]
It is still weird, because as I understand it, the plams.job status is not read anymore after getting the property. It is about the qmworks.Result.status which is now properly serialized, therefore read from the cache, and not from plams.

Satesh, where exactly were you querying the status from?

**Comment by felipeZ** [comment]
I was doing it with Satesh and we are printed the results inside the [__getattr__](https://github.com/SCM-NV/qmworks/blob/develop/qmworks/packages/packages.py#L97) method for the [Result](https://github.com/SCM-NV/qmworks/blob/develop/qmworks/packages/packages.py#L47) class in qmworks.

**Comment by ridderl** [comment]
Clear. I'm curious how this happens :-)

**Comment by jhidding** [comment]
I'm still clueless what happens here. The more bugs we get like this, I get more frustrated, because it has nothing to do with the project, but with stupid design errors in plams.
