### ISSUE TITLE
Settings from QMWORKS vs Settings from Plams

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#6]
In the class [Settings](https://github.com/SCM-NV/qmworks/blob/master/qmworks/settings.py) we have several methods that modify the behaviour of *Plams.Settings*. Do we still need these modifications after merging our changes in the escience branch with the Main branch?

**Comment by ridderl** [comment]
I will have to check, but I think the merge is not yet done ...

**Comment by felipeZ** [comment]
Great! I will add those functions to the init.py file

**Comment by ridderl** [comment]
We still need the QMworks settings. See my comments added in qmworks/settings.py
