### ISSUE TITLE
Case sensitivity of functional names in qmworks

### ISSUE THREAD

**Issue by sgu800** [SCM-NV/qmworks#62]
Dear All,

Qmworks is giving an error when we type name of functional in upper case letters (e.g. BLYP). It is only working when we use all lower case letters to define functions (e.g. blyp instead of BLYP). We should get make them case insensitive.

Kind regards,
Satesh

**Comment by felipeZ** [comment]
I think we should convert the user input to lower case because most packages are case insensitive (DIRAC is case sensitive). Then we can merge the user ``Settings`` with the template.
