### ISSUE TITLE
Shared state between calculations

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#83]
I have found that when running the states the [Settings](https://github.com/SCM-NV/qmworks/blob/develop/src/qmworks/settings.py) are somehow sharing the state of previous runs. For instance the following is the input generated for a CP2K single point calculation using the this [test](https://github.com/SCM-NV/qmworks/blob/develop/test/test_using_plams/test_mo_cp2k.py#L63) 
```
&FORCE_EVAL
  &DFT
    BASIS_SET_FILE_NAME  /home/user/.test_qmworks/BASIS_MOLOPT
    &MGRID
      CUTOFF  400
      NGRIDS  4
    &END
```
This input is correct but when I run some ADF test calculations before I got the following input:
```
&FORCE_EVAL
  DFT  bp86
  &SUBSYS
    &COORD
C  -2.58000000e+00   6.80000000e-02   0.00000000e+00
```
Somehow the Settings are being shared between calculations.

**Comment by ridderl** [comment]
The above commit might fix this problem? The bp86 functional is set in the ADF3FDE_cystine example. The bug in the ADF3FDE code resulted in an update of the template.singlepoint. This is avoided now, and I would not be surprised if that fixes (at least part of) this issue.

**Comment by felipeZ** [comment]
Fixed
